### ISSUE TITLE
Converting timestamp format 1 BC is different on some archtectures

### ISSUE THREAD

**Issue by ged** [ged/ruby-pg#284]
**[Original report](https://bitbucket.org/ged/ruby-pg/issue/284) by Jun Aruga (Bitbucket: [junaruga](https://bitbucket.org/junaruga), GitHub: [junaruga](https://github.com/junaruga)).**

----------------------------------------

I tried to build and run tests on latest version pg v1.1.3 for several architectures. [1]

```
Fedora rawhide (development version)
Ruby: 2.5.1
libpq-devel: 8.2.1
```

But below assertion in the rspec spec files is failed on some architectures (`i686` and `arm7hl`) and format = 1. And it is okay on other architectures (x86_64, ppc64le, aarch64, s390x) or format = 0.

```
res = @conn.exec_params( "SELECT CAST('4714-11-24 23:58:59.1231-03 BC' AS TIMESTAMP WITHOUT TIME ZONE)", [], format )
expect( res.getvalue(0,0).iso8601(3) ).to eq( Time.utc(-4713, 11, 24, 23, 58, 59.1231).iso8601(3) )
```

```
Failures:
  1) Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 1 timestamps per TimestampUtcToLocal
     Failure/Error: expect( res.getvalue(0,0).iso8601(3) ).to eq( Time.utc(-4713, 11, 24, 23, 58, 59.1231).getlocal.iso8601(3) )
       expected: "-4713-11-24T23:58:59.123+00:00"
            got: "1956-11-26T05:04:03.123+00:00"
       (compared using ==)
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:79:in `block (6 levels) in <top (required)>'
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:15:in `restore_type'
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:74:in `block (5 levels) in <top (required)>'
     # ./spec/helpers.rb:30:in `block in included'
  2) Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 1 timestamps with time zone
     Failure/Error: expect( res.getvalue(0,0) ).to be_within(1e-3).of( Time.new(-4713, 11, 24, 23, 58, 59.1231, "-03:00").getlocal )
       expected 1956-11-26 08:04:03.123100000 +0000 to be within 0.001 of -4713-11-25 02:58:59 +0000
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:99:in `block (5 levels) in <top (required)>'
     # ./spec/helpers.rb:30:in `block in included'
  3) Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 1 timestamps per TimestampUtc
     Failure/Error: expect( res.getvalue(0,0).iso8601(3) ).to eq( Time.utc(-4713, 11, 24, 23, 58, 59.1231).iso8601(3) )
       expected: "-4713-11-24T23:58:59.123Z"
            got: "1956-11-26T05:04:03.123Z"
       (compared using ==)
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:67:in `block (6 levels) in <top (required)>'
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:15:in `restore_type'
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:44:in `block (5 levels) in <top (required)>'
     # ./spec/helpers.rb:30:in `block in included'
  4) Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 1 timestamps per TimestampLocal
     Failure/Error: expect( res.getvalue(0,0).iso8601(3) ).to eq( Time.new(-4713, 11, 24, 23, 58, 59.1231).iso8601(3) )
       expected: "-4713-11-24T23:58:59.123+00:00"
            got: "1956-11-26T05:04:03.123+00:00"
       (compared using ==)
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:91:in `block (6 levels) in <top (required)>'
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:15:in `restore_type'
     # ./spec/pg/debug_basic_type_mapping_timestamp_bc_spec.rb:86:in `block (5 levels) in <top (required)>'
     # ./spec/helpers.rb:30:in `block in included'
```

Attached file is to be copied and trimmed from `spec/pg/basic_type_mapping_spec.rb`.

Right now I am debugging it seeing postgresql official documents [2][3]

Want I would like to ask you is

* Can you assume which part in the code has weird smell?
* I am not familiar with debugging with PG C library. Below `PQgetvalue` displayed the wrong encoding value (?). Do you know how to fix it?

ext/pg_connection.c

```
printf("[DEBUG] pg_connection.c  pgconn_get_last_result PGresult (prev) value: [%s]\n", PQgetvalue(prev, 0, 0));
```

```
[DEBUG] pg_connection.c  pgconn_get_last_result PGresult (prev) value: [�|�[V�]
```

When using `psql` command, the value was same between each architectures with as "BC" string.

```
echo "SELECT CAST('4714-11-24 23:58:59.1231-03 BC' AS TIMESTAMP WITHOUT TIME ZONE);" | psql --host=localhost --port=54321 test
           timestamp          
-----------------------------
 4714-11-24 23:58:59.1231 BC
```

Thank you for your help.

* [1] build.log https://koji.fedoraproject.org/koji/taskinfo?taskID=29797654
* [2] https://www.postgresql.org/docs/10/static/datatype-datetime.html
* [3] https://www.postgresql.org/docs/10/static/libpq-exec.html
* [4] https://github.com/junaruga/ruby-pg/commit/905f7bfd546466fe1e8b0fa030700e20491ffec9#diff-604f8ab697e4e5a079a4eaa09943d2feR3151
