### ISSUE TITLE
async_exec doesn't process signals when waiting on pgconn_discard_results

### ISSUE THREAD

**Issue by drdrsh** [ged/ruby-pg#355]
Hi,

I am not sure if this is a bug or expected behavior.

I am investigating a case where a Puma worker thread seems to "disappear" from logs only to re-appear after puma gets a termination signal. During that time the thread doesn't log anything and does not process signals sent through `Thread.raise`. 

So while I was trying to reproduce this issue I stumbled upon a situation where `async_exec` blocks indefinitely and doesn't process signals (similar to the case described above) if `pgconn_discard_results` doesn't get response from the server.

I used `docker pause` to get this behavior

This is my docker-compose set up
```
version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: test
      POSTGRES_USER: user

  bouncer :
    image: edoburu/pgbouncer
    links:
      - db
    ports:
      - 6000:5432
    environment:
      AUTH_TYPE: any
      LOG_CONNECTIONS: 1
      LOG_DISCONNECTIONS: 1
      DATABASE_URL: "postgres://user:pass@db/test"
      POOL_MODE: "transaction"
      SERVER_RESET_QUERY: "DISCARD ALL;"
      SERVER_RESET_QUERY_ALWAYS: 1
      MAX_DB_CONNECTIONS: 1
      DEFAULT_POOL_SIZE: 1
      MIN_POOL_SIZE: 1
      CLIENT_LOGIN_TIMEOUT: 25
      QUERY_WAIT_TIMEOUT: 25
```

and this is the my ruby file

```
require 'pg'
require 'timeout'

STDOUT.sync = true

pg_connection = PG::Connection.open(dbname: 'test', host: 'localhost', port: 6000, user: "user", password: "pass")
sleep(10) # wait for DB

loop do
  File.open("/tmp/trace", "w+") do |f|
    f.sync = true
    begin
      pg_connection.trace(f)
      puts "Querying DB with 1 second timeout"
      Timeout.timeout(1, Exception) { pg_connection.async_exec("SELECT 1") }
    rescue Exception => e
      puts "Encountered an excetion #{e}"
    end
    puts "Done"
    puts `cat /tmp/trace`
  end
  puts "Waiting for 5 seconds before retrying"
  sleep 5
end
```
Running `docker-compose pause bouncer` will cause `async_exec` to block and not respond to the timeout exception. I stepped through the c extension and the thread was blocked on `pgconn_discard_results` call 
https://github.com/ged/ruby-pg/blob/9cf9d8aabd4a1a95ef2bc7c61054fc2cc663072b/ext/pg_connection.c#L3198

Below is the stack trace as observed by lldb
```
 frame #0: 0x00007fff712543d6 libsystem_kernel.dylib`poll + 10
    frame #1: 0x00000001060863a0 libpq.5.dylib`pqSocketCheck + 237
    frame #2: 0x000000010608627c libpq.5.dylib`pqWaitTimed + 21
    frame #3: 0x00000001060839ca libpq.5.dylib`PQgetResult + 99
    frame #4: 0x000000010603a351 pg_ext.bundle`gvl_PQgetResult_skeleton(data=0x00007ffeefbfe640) at gvl_wrappers.c:13:1
    frame #5: 0x0000000100314fbb libruby.2.7.dylib`rb_nogvl(func=<unavailable>, data1=<unavailable>, ubf=(libruby.2.7.dylib`ubf_select at thread_pthread.c:1275), data2=0x0000000100707270, flags=<unavailable>) at thread.c:1475:5
    frame #6: 0x000000010603a32d pg_ext.bundle`gvl_PQgetResult(conn=<unavailable>) at gvl_wrappers.c:14:1
    frame #7: 0x0000000106041c8e pg_ext.bundle`pgconn_discard_results(self=<unavailable>) at pg_connection.c:3150:16
    frame #8: 0x000000010604052b pg_ext.bundle`pgconn_async_exec(argc=1, argv=0x0000000101800178, self=4379180840) at pg_connection.c:3198:2
    frame #9: 0x0000000100367f70 libruby.2.7.dylib`vm_call_cfunc [inlined] vm_call_cfunc_with_frame(ec=<unavailable>, reg_cfp=<unavailable>, calling=<unavailable>, cd=<unavailable>) at vm_insnhelper.c:2514:11
    frame #10: 0x0000000100367e54 libruby.2.7.dylib`vm_call_cfunc(ec=0x00000001007074f0, reg_cfp=0x00000001018ffe08, calling=<unavailable>, cd=<unavailable>) at vm_insnhelper.c:2539
    frame #11: 0x000000010034ddff libruby.2.7.dylib`vm_exec_core [inlined] vm_sendish(ec=<unavailable>, reg_cfp=<unavailable>, cd=0x0000000104f95370, block_handler=0) at vm_insnhelper.c:4023:11
    frame #12: 0x000000010034ddb0 libruby.2.7.dylib`vm_exec_core(ec=<unavailable>, initial=<unavailable>) at insns.def:801
    frame #13: 0x0000000100362d8c libruby.2.7.dylib`rb_vm_exec(ec=0x00000001007074f0, mjit_enable_p=<unavailable>) at vm.c:0
```

I don't have evidence that this behavior is the root cause for the original issue I was debugging but I find it odd that there is a case where `async_exec` behaves like `sync_exec` so I thought I'd report it.
